### ISSUE TITLE
Authentication Information

### ISSUE THREAD

**Issue by hhn-admin** [tonywagner/EPlusTV#26]
The new release sounds amazing! 

Gave it a try but only seeing this in the logs: 

![image](https://user-images.githubusercontent.com/109996534/194175296-762152d4-f7f3-41f1-a92a-31572dd9f3a1.png)

Are these the correct logs to be able to see how to authenticate?

Thanks for your work on this project!

**Comment by m0ngr31** [comment]
That the old version. Make sure you do a fresh pull

**Comment by rayusrnm** [comment]
I also got this at first since I was trying to install a separate image.  Once I deleted the old image and pulled the new image it pulled and went as expected.  I still use Start_Channel= but this is the only variable I set.   Make sure you do pay attention to the output to get your activation code.  (This is just like adding a roku, android or firestick to an app)
