### ISSUE TITLE
First Time Setup Question w/xTeVe & Plex + unRaid

### ISSUE THREAD

**Issue by Healzangels** [tonywagner/EPlusTV#35]
Hello!

First off thanks for the very awesome sounding piece of software. I've been running into a bit of an issue on I believe the final steps to get everything working. 

My setup is currently entirely in unRaid

EPlus seems to be up and running fine "Server started on port 8000" 
I then added the address `http://10.0.1.98:8000/channels.m3u` to xTeVe which came up showing 100 streams. 
Followed the same steps for XMLTV with xTeVe entering `http://10.0.1.98:8000/xmltv.xm`l

On Plex I then added my xTeVe tuner which properly showed my newly assigned channels. 

However when I go to access the channel I receive an error stating`Could not tune channel. Please check your tuner or antenna.`
From xTeVe logs I see:
EPlusTV 9
[xTeVe] Client User-Agent:      Lavf/LIBAVFORMAT_VERSION
[xTeVe] Streaming URL:          http://10.0.1.98:8000/channels/9.m3u8
[xTeVe] Streaming Info:         URL was passed to the client.
[xTeVe] Streaming Info:         xTeVe is no longer involved, the client connects directly to the streaming server.

Navigating to `http://10.0.1.98:8000/channels/9.m3u8` I do get a clip that can be opened within VLC but no luck connecting via Plex. 

Appreciate any tips to over come this final hurdle. Let me know if there are any additional details I can provide. Thanks

**Comment by SoSJames** [comment]
I believe your problem is with Plex, as it's known to have difficulty with live TV streams on occasion. If you can play the links in VLC, the xTeVe setup is probably fine. You should start by looking at Plex's log to find the specific error that causes the failure when you try to play a stream. You can also try to activate the buffer function in xTeVe with either ffmpeg or VLC, which might help Plex to figure out the stream.  

I do have a question, however. You said you can see a clip in VLC, but is it the "Event Will Start Soon" screen created by EplusTV? Or are you actually seeing a live stream from ESPN+? I ask because on my setup (with Jellyfin) the streams will often start on the first screen, then stall, and opening the same channel again will then play the live feed. I think it's because the difference between the two video clips causes Jellyfin's ffmpeg to quit. Perhaps something similar is going on with Plex?

**Comment by Healzangels** [comment]
Thanks for the suggestions! I'll take a peak at my logs this afternoon and report back. Should have thought to look through the Plex side D'oh! 

I did setup dizqueTV w/xTeVe as a test and confirmed those streams did play. Which falls inline with what you had mentioned checking my ffmpeg settings on xTeVe side as did configure those for dizqueTV.

As for the dled clip when I play through VLC I see the sports event you'd expect to see on the channel. Did happen to notice when I clicked let the error occur then try again w/the stream via Plex it did seem to attempt to load (further load?) when accessing but again would fail. 

Will follow up. Thanks again

**Comment by Healzangels** [comment]
Apologies for the delayed follow-up. Looks like changing the buffer option in xTeVe to ffmpeg did the trick! Thanks for the suggestion. I am seeing the Event Will Start Soon text occasionally and having to back out and back in but sounds like that's the nature of the beast. 

Thanks again
